### ISSUE TITLE
improving prime number validation system

### ISSUE THREAD

**Issue by IvaNG515** [IvaNG515/RustProj#1]
the current prime number validation system loops through every number that is >= than usr_num
`while usr_num - possible_factor != -1 {
            if usr_num % possible_factor != 0 {
                possible_factor += 1;
            }
            if usr_num % possible_factor == 0 {
                how_factors += 1;
                possible_factor += 1;
            }
        }
`
want to validate via looking if how_factors is > 3 then break out of loop, bc it's not prime

**Comment by 101Edwin** [comment]
Remove duplicated codes ^_^
